name: dartforcehelloworld
description: A sample command-line application
dependencies:
  http: '>=0.9.0 <0.10.0'
  http_server: '>=0.9.0 <0.10.0'
  logging: '>=0.9.0 <0.10.0'
  force: 
    git: git://github.com/jorishermans/dart-force.git  
